# Generated by Django 4.2 on 2023-05-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("htmldb", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Page", new_name="Pages",),
    ]
