# Generated by Django 4.2 on 2023-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmldb", "0002_rename_page_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="name",
            field=models.CharField(default="Index", max_length=50, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pages",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
