# Generated by Django 4.2 on 2023-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        default="Какое это число: положительное, отрицательное, ноль?",
                        editable=False,
                        max_length=255,
                        verbose_name="Формулировка  задачи",
                    ),
                ),
                ("num", models.FloatField(verbose_name="Вещественное число")),
                (
                    "current_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("-id",),
            },
        ),
    ]
