# Generated by Django 4.2 on 2023-05-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(
                default="Какое это число: положительное, отрицательное, ноль?",
                max_length=255,
                verbose_name="Формулировка  задачи",
            ),
        ),
    ]
